### ISSUE TITLE
Fix checklist

### ISSUE THREAD

**Issue by vitiral** [civboot/fngi#9]
Here are a few small changes/tweaks that are on my mind:

* [ ] Add TyDbNow, track and check types at compile time. It is impossible to turn off the type checker at compile time.
* [ ] Don't throw away locals metadata. Simplifies generics, is good for native compilation and practically necessary for debugging.
  * Store it on the TyFn (new field)
* [ ] Support Role directly in fngi
  * need to create Sp_UFile and Sp_BufFile implementations that are callable from fngi/spor
  * add functions to call the native version if it is available, else 

```
#define Sp_Xr(ROLE, METHOD) \
  do { WS_ADD((ROLE)->d); executeFn(k, (ROLE)->METHOD); } while(0)

#define Sp_Xr1(ROLE, METHOD, ARG) \
  do { WS_ADD((ROLE)->d); WS_ADD(ARG); executeFn(k, (ROLE)->METHOD); } while(0)

// ... etc as needed

void spRead(Sp_Reader* r) {
  if (r->m == &mSp_UFile)        return UFile_read(r->d);
  else if (r->m == &mSp_BufFile) return BufFile_read(r->d);
  Sp_Xr(r,read);
}
```

* [ ] Debug support
  * [ ] Str libraries (concat, search, etc)
  * [ ] Error handling - starts new fiber and inspect broken one
  * [ ] inspection helpers: print inspected locals, etc
  * [ ] TokenLoc: store locations of tokens in a file for later lookup / debugging (dbgRs)
* [ ] Operator functions: if struct, check for method of same name. I.e. a + b calls a.+ b. This will be implemented directly in code (C macro)
* [ ] civc
  * [ ] rename Bst -> CBst (CStr key)
  * [ ] BStk: a stack that uses blocks directly and grows and shrinks as needed. This should be the basic Stk type for the return Stk. Basically is a LL of blocks, each with a sp and next (cap not needed). This allows for the return-stack (RS) to grow and shrink as needed.
* [ ] Struct
  * [ ] add `using` syntax for definition inside sub-dictionary
    * `using myMod fn myFn ... do ( ... )`
    * `using myMod ( ... structs/functions ... )`
    * localsDict NEEDS to be a separate Kern field for handling variables inside of using clauses!
  * [ ] support methods
* [ ] Generic types
  * [ ] add TyMod (TY_DICT_MOD) type
  * [ ] If a TyMod isn't doing lookup (i.e `mod.foo`), then it's `fields` may point to a function (asNow isTy -> &Ty). This is executed to get the type in a type context, or to get the type to compile in the compiler context!
  * [ ] syn methods: they are passed (var: &Var, asNow). If var is null, then it's a reference access (just get TyDb_top). They can then compile correct behavior (i.e. a local Arr type can modify local values).
  * [ ] Therefore you can do `var a: Arr[S, 20]; a.init {1, 2, 3}`
* [ ] Generic methods: methods for the appropriate SIZES are generated as sub-types for the type, i.e. Bst._Bst[20]. The actual  dictionary entries and typespecs are created correctly, i.e. Bst.Bst[MyStruct] (the key must be aliased and is not directly accessible)
* [ ] Support a "stack" of srcFile's to be used ONLY for text-macros
  * when parsing, items are moved into the token Buf. If the file is exhausted, it is dropped and the next file down is used.
  * text macros need a special function type -- they are executed immediately in `scan` and the scan is simply re-run when they are encountered. Actually, move from TY_FN_COMMENT to TY_FN_TEXT, since that is essentially what COMMENT type functions already do!
